# Default values for mssql-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

nameOverride: ''
fullnameOverride: ''

image:
  repository: mcr.microsoft.com/mssql/server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2019-latest"

nodeSelector: {}

tolerations: []

ACCEPT_EULA:
    value: "y"
MSSQL_PID:
    value: "Developer"
MSSQL_AGENT_ENABLED:
    value: "true"
hostname: mssqllatest
sa_password: "Toughpass1!"
containers:
  ports:
      containerPort: 1433

podAnnotations: {}

podSecurityContext:
   fsGroup: 10001

service:
  type: LoadBalancer
  port: 1433
  annotations: {}

pvc:
 StorageClass: ""
 dataaccessMode: ReadWriteOnce
 datasize: 5Gi
 logaccessMode: ReadWriteOnce
 logsize: 5Gi
 dumpaccessMode: ReadWriteOnce
 dumpsize: 2Gi
 backupaccessMode: ReadWriteOnce
 backupsize: 2Gi


