apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sql-statefull-deploy.name" . }}-secret
  labels:
    {{- include "sql-statefull-deploy.labels" . | nindent 4 }}
type: Opaque
data:
 sa_password : {{ .Values.sa_password | b64enc | quote}}