{
 "title": "SQL Server Dashboard",
 "description": "This Dashboard is for SQL on VM's or On-premise SQL Server/containers",
 "tags": [ "SQLMI" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "InstanceName",
    "label": "InstanceName",
    "query": " select sql_instance from (select  \"sql_instance\", LAST(\"engine_edition\")  from \"sqlserver_server_properties\" where  \"engine_edition\" = 3 and $timeFilter  GROUP BY sql_instance)"
   }
  ]
 },
 "panels": [
  { "title": " Instance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "InstanceName" },
  {
   "title": "Virtual Cores",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "cpu_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Server Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "query": "SELECT last(\"server_memory\") FROM \"sqlserver_server_properties\" WHERE (\"sql_instance\" =~ /^$InstanceName$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "server_memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Service Tier",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "query": "SHOW TAG VALUES WITH KEY = \"sku\" WHERE \"sql_instance\" =~ /^$InstanceName$/  AND $timeFilter",
     "select": [
      [
       { "params": [ "TotalStorageMB" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Hardware_Type",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 1 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "query": "SHOW TAG VALUES WITH KEY = \"hardware_type\" WHERE \"sql_instance\" =~ /^$InstanceName$/  AND $timeFilter",
     "select": [
      [
       { "params": [ "total_storage_mb" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "# Databases",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "query": "SELECT last(\"db_online\") FROM \"sqlserver_server_properties\" WHERE (\"sql_instance\" =~ /^$InstanceName$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "db_online" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Available  Storage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "sqlserver_volume_space",
     "select": [
      [
       { "params": [ "available_space_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "SQL Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true
  },
  {
   "title": "Batch Requests/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_counter",
     "groupBy": [
      { "params": [ "counter" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT non_negative_derivative(\"value\", 1s) FROM \"sqlserver_performance\" WHERE (\"sql_instance\" =~ /^$InstanceName$/ AND \"object\" =~ /SQL Statistics/) AND $timeFilter GROUP BY \"counter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      {
       "condition": "AND",
       "key": "object",
       "operator": "=",
       "value": "MSSQL$C8648930B0D8:SQL Statistics"
      }
     ]
    }
   ]
  },
  {
   "title": "Transactions/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "counter", "operator": "=", "value": "Transactions/sec" },
      { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  { "title": "CPU and Queueing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Total %CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "%CPU Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT sum(\"value\") FROM \"sqlserver_performance\" WHERE (\"sql_instance\" =~ /^$InstanceName$/ AND \"object\" =~ /Resource Pool Stats/ AND  \"counter\" = 'CPU usage %') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "CPU usage %" }
     ]
    }
   ]
  },
  {
   "title": "Workload Group - %CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT \"value\" FROM \"sqlserver_performance\" WHERE (\"counter\" = 'CPU usage %' AND \"object\" =~ /Workload Group Stats/ AND \"sql_instance\" =~ /^$InstanceName$/) AND $timeFilter GROUP BY \"instance\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "counter", "operator": "=", "value": "CPU usage %" },
      { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  { "title": "Waits and Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Wait Types",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_wait_type",
     "groupBy": [
      { "params": [ "wait_type" ], "type": "tag" }
     ],
     "measurement": "sqlserver_waitstats",
     "query": "SELECT non_negative_derivative(\"wait_time_ms\", 1s) FROM \"sqlserver_waitstats\" WHERE (\"sql_instance\" =~ /^$InstanceType.*$/) AND $timeFilter GROUP BY \"wait_type\"",
     "select": [
      [
       { "params": [ "wait_time_ms" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Signal Wait Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_wait_type",
     "groupBy": [
      { "params": [ "wait_type" ], "type": "tag" }
     ],
     "measurement": "sqlserver_waitstats",
     "select": [
      [
       { "params": [ "signal_wait_time_ms" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Waiting Tasks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_wait_type",
     "groupBy": [
      { "params": [ "wait_type" ], "type": "tag" }
     ],
     "measurement": "sqlserver_waitstats",
     "select": [
      [
       { "params": [ "waiting_tasks_count" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Log Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true
  },
  {
   "title": "Log  Flushed Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Log Bytes Flushed/sec" }
     ]
    }
   ]
  },
  {
   "title": "Log Flushes/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "counter", "operator": "=", "value": "Log Flushes/sec" },
      { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Schedulers ( Optional)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scheduler Delay ms/sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_scheduler_id",
       "groupBy": [
        { "params": [ "scheduler_id" ], "type": "tag" }
       ],
       "measurement": "sqlserver_schedulers",
       "select": [
        [
         { "params": [ "total_scheduler_delay_ms" ], "type": "field" },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
       ]
      }
     ]
    },
    {
     "title": "Runnable Task Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_scheduler_id",
       "groupBy": [
        { "params": [ "scheduler_id" ], "type": "tag" }
       ],
       "measurement": "sqlserver_schedulers",
       "select": [
        [
         { "params": [ "runnable_tasks_count" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
       ]
      }
     ]
    },
    {
     "title": "Scheduler CPU ms/sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_scheduler_id",
       "groupBy": [
        { "params": [ "scheduler_id" ], "type": "tag" }
       ],
       "measurement": "sqlserver_schedulers",
       "select": [
        [
         { "params": [ "total_cpu_usage_ms" ], "type": "field" },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
       ]
      }
     ]
    },
    {
     "title": "Context switches/sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_scheduler_id",
       "groupBy": [
        { "params": [ "scheduler_id" ], "type": "tag" }
       ],
       "measurement": "sqlserver_schedulers",
       "select": [
        [
         { "params": [ "context_switches_count" ], "type": "field" },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "database_name", "operator": "=~", "value": "/^$DatabaseName$/" },
        { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Memory Manager",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_counter",
     "groupBy": [
      { "params": [ "counter" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT \"value\" FROM \"sqlserver_performance\" WHERE (\"object\" =~ /Memory Manager/ AND \"sql_instance\" =~ /^$InstanceName$/) AND $timeFilter GROUP BY \"counter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "object",
       "operator": "=",
       "value": "MSSQL$B60900B20CD7:Memory Manager"
      },
      { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Clerks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_clerk_type",
     "groupBy": [
      { "params": [ "clerk_type" ], "type": "tag" }
     ],
     "measurement": "sqlserver_memory_clerks",
     "select": [
      [
       { "params": [ "size_kb" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Buffer Manager: Page Life Expectancy",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "counter", "operator": "=", "value": "Page life expectancy" },
      { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Buffer Manager",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_counter",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT non_negative_derivative(\"value\", 1s)  FROM \"sqlserver_performance\" WHERE (\"object\"  =~ /Buffer Manager/ AND \"sql_instance\" =~ /^$InstanceName$/ AND \"counter\" =~ /sec/ ) AND $timeFilter GROUP BY \"counter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "object",
       "operator": "=",
       "value": "MSSQL$B60900B20CD7:Buffer Manager"
      },
      { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Page lookups/sec" }
     ]
    }
   ]
  },
  {
   "title": "Access Methods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_counter",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT non_negative_derivative(\"value\", 1s)  FROM \"sqlserver_performance\" WHERE (\"object\"  =~ /Access Methods/ AND \"sql_instance\" =~ /^$InstanceName$/ AND \"counter\" =~ /sec/ ) AND $timeFilter GROUP BY \"counter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "SQL Statistics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_counter",
     "groupBy": [
      { "params": [ "counter" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT non_negative_derivative(\"value\", 1s) FROM \"sqlserver_performance\" WHERE (\"sql_instance\" =~ /^$InstanceName$/ AND \"object\" =~ /General Statistics/) AND $timeFilter GROUP BY \"counter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      {
       "condition": "AND",
       "key": "object",
       "operator": "=",
       "value": "MSSQL$C8648930B0D8:General Statistics"
      }
     ]
    }
   ]
  }
 ]
}