kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
     name: {{ .Values.pvc.StorageClass }}
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed