apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
  labels:
    {{- include "mssql-latest.labels" . | nindent 4 }}
type: Opaque
data:
 sa_password : {{ .Values.MSSQL_SA_PASSWORD | b64enc | quote}}
