apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
  labels:
    {{- include "sql-server-rancher.labels" . | nindent 4 }}
type: Opaque
data:
  mssql_sa_password : {{ .Values.mssql.sa.password | b64enc | quote }}
