# Default values for mssql-latest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

image:
  repository: mcr.microsoft.com/mssql/server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2019-latest"

ACCEPT_EULA:
    value: "y"
MSSQL_PID:
    value: "Developer"
MSSQL_AGENT_ENABLED:
    value: "true"
hostname: mssqllatest
mssql_sa_password: "Toughpass1!"
containers:
  ports:
      containerPort: 1433

podAnnotations: {}

podSecurityContext:
   fsGroup: 10001

service:
  type: LoadBalancer
  port: 1433

pvc:
 StorageClass: "azure-disk"
 userdbaccessMode: ReadWriteOnce
 userdbsize: 5Gi
 userlogaccessMode: ReadWriteOnce
 userlogsize: 5Gi
 tempdbaccessMode: ReadWriteOnce
 tempsize: 2Gi
 mssqldataaccessMode: ReadWriteOnce
 mssqldbsize: 2Gi


