apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mssql-latest.fullname" . }}
  labels:
    {{- include "mssql-latest.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      {{- include "mssql-latest.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mssql-latest.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 6 }}
      {{- end }}
      hostname: {{ .Values.hostname}}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command:
            - /bin/bash
            - -c
            - cp /var/opt/config/mssql.conf /var/opt/mssql/mssql.conf && /opt/mssql/bin/sqlservr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containers.ports.containerPort}}
          env:
           - name: MSSQL_PID
             value: "{{ .Values.MSSQL_PID.value}}"
           - name: ACCEPT_EULA
             value: "{{ .Values.ACCEPT_EULA.value | upper}}"
           - name: MSSQL_AGENT_ENABLED
             value: "{{ .Values.MSSQL_AGENT_ENABLED.value}}"
           - name: SA_PASSWORD
             valueFrom:
               secretKeyRef:
                name: mssql-secret
                key: {{  template "mssql.sapassword" . }}
          volumeMounts:
           - name: mssqldata
             mountPath: /var/opt/mssql/data/db
           - name: mssqllog
             mountPath: /var/opt/mssql/data/log
           - name: mssqldump
             mountPath: /var/opt/mssql/data/dump
           - name: mssqlbackup
             mountPath: /var/opt/mssql/data/basckup
           - name: mssql-config-volume
             mountPath: /var/opt/config
      volumes:
       - name: mssqldata
         persistentVolumeClaim:
           claimName: mssql-data
       - name: mssqllog
         persistentVolumeClaim:
           claimName: mssql-log
       - name: mssqldump
         persistentVolumeClaim:
           claimName: mssql-dump
       - name: mssqlbackup
         persistentVolumeClaim:
           claimName: mssql-backup
       - name: mssql-config-volume
         configMap:
          name: mssql-config
