kind: ConfigMap 
apiVersion: v1 
metadata:
  name: mssql-config
data:
  mssql.conf: |
    [EULA]
    accepteula = Y
    accepteulaml = Y
    
    [coredump]
    captureminiandfull = true
    coredumptype = full
    
    [hadr]
    hadrenabled = 1
    
    [language]
    lcid = 1033
    
    [filelocation]
    defaultdatadir = /var/opt/mssql/db/data
    defaultlogdir = /var/opt/mssql/db/log
    defaultdumpdir = /var/opt/mssql/db/dump
    defaultbackupdir = /var/opt/mssql/db/backup
