apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mssql-server.name" . }}-secret
  labels:
    {{- include "mssql-server.labels" . | nindent 4 }}
type: Opaque
data:
 sa_password : {{ .Values.sa_password | b64enc | quote}}