## 
# Thank you to our SUSE Partners for helping with this :)
##Assumptions
# 1. use a matching version to the underlying build host
# 2. ensure it is registered to have access to needed repos
#	then leveraging container-suseconnect-zypp
#	e.g. zypper ref
#	Repository 'SLE-Module-Containers12-Pool' is up to date.
#	Repository 'SLE-Module-Containers12-Updates' is up to date.
#	Repository 'SLES12-SP5-Pool' is up to date.
#	Repository 'SLES12-SP5-Updates' is up to date.
#	All repositories have been refreshed.
# 3. minimize the layers by consolidating commands

##
# Base image
##
# Start with the appropriate base image
FROM registry.suse.com/suse/sles12sp5

# add a needed (beyon minimal) dependency package this package is need so setcap can be used later on to provide the required privilages
RUN zypper in --no-confirm libcap-progs

##
# Install the latest SQL 2019 build on SLES
##
# Add product repos / packages
#	zypper refresh && \

RUN zypper addrepo --no-gpgcheck --refresh --check https://packages.microsoft.com/config/sles/12/mssql-server-2019.repo && \
	zypper --non-interactive install --no-confirm --auto-agree-with-licenses --auto-agree-with-product-licenses mssql-server

RUN zypper addrepo --no-gpgcheck --refresh --check https://packages.microsoft.com/config/sles/12/prod.repo && \
        ACCEPT_EULA=Y zypper --non-interactive install  mssql-tools

# post the installation of SQL Server the mssql user/group is created
# so set the right permissions to the msssql folder
#
RUN mkdir -p -m 770 /var/opt/mssql && chown -R mssql. /var/opt/mssql
 
# Grant sql the permissions to connect to ports <1024 as a non-root user
#
RUN setcap 'cap_net_bind_service+ep' /opt/mssql/bin/sqlservr
 
# Allow dumps from the non-root process
#
RUN setcap 'cap_sys_ptrace+ep' /opt/mssql/bin/paldumper
RUN setcap 'cap_sys_ptrace+ep' /usr/bin/gdb
 
#ldconfig file because setcap causes the os to remove LD_LIBRARY_PATH
# and other env variables that control dynamic linking
#
RUN mkdir -p /etc/ld.so.conf.d && touch /etc/ld.so.conf.d/mssql.conf
RUN echo -e "# mssql libs\n/opt/mssql/lib" >> /etc/ld.so.conf.d/mssql.conf
RUN ldconfig
 
EXPOSE 1433
 
USER mssql
 
CMD ["/opt/mssql/bin/sqlservr"]
