# SQL Server Command Line Tools
FROM alpine

LABEL maintainer="SQL Server Engineering Team"

RUN echo "Installing needed software"
    && apk update --no-cache \
    && add --no-cache curl gnupg && \

    echo "Download the desired package(s)" \
    && curl -O https://download.microsoft.com/download/b/9/f/b9f3cce4-3925-46d4-9f46-da08869c6486/msodbcsql18_18.0.1.1-1_amd64.apk \
	&& curl -O https://download.microsoft.com/download/b/9/f/b9f3cce4-3925-46d4-9f46-da08869c6486/mssql-tools18_18.0.1.1-1_amd64.apk && \

    echo "(Optional) Verify signature, if 'gpg' is missing install it using 'apk add gnupg':" \
    && curl -O https://download.microsoft.com/download/b/9/f/b9f3cce4-3925-46d4-9f46-da08869c6486/msodbcsql18_18.0.1.1-1_amd64.sig \
	&& curl -O https://download.microsoft.com/download/b/9/f/b9f3cce4-3925-46d4-9f46-da08869c6486/mssql-tools18_18.0.1.1-1_amd64.sig && \

    echo "Verifying signature." \
    && curl https://packages.microsoft.com/keys/microsoft.asc  | gpg --import - \
	&& gpg --verify msodbcsql18_18.0.1.1-1_amd64.sig msodbcsql18_18.0.1.1-1_amd64.apk \
	&& gpg --verify mssql-tools18_18.0.1.1-1_amd64.sig mssql-tools18_18.0.1.1-1_amd64.apk && \

    echo "Installing the package(s)" \
    && apk add --no-cache --allow-untrusted msodbcsql18_18.0.1.1-1_amd64.apk \
	&& apk add --no-cache --allow-untrusted mssql-tools18_18.0.1.1-1_amd64.apk \
	&& rm -f msodbcsql18_18.0.1.1-1_amd64.apk mssql-tools18_18.0.1.1-1_amd64.apk

CMD ["/bin/bash"]
