# SQL Server Command Line Tools
FROM redhat/ubi8

LABEL maintainer="SQL Server Engineering Team"

# adding custom MS repository
RUN yum install -y https://packages.microsoft.com/config/rhel/8/packages-microsoft-prod.rpm

# install SQL Server drivers and tools
RUN ACCEPT_EULA=Y yum install -y msodbcsql18 mssql-tools18

# add the binary location to the $PATH
RUN echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc
RUN /bin/bash -c "source ~/.bashrc"

CMD /bin/bash 
